### ISSUE TITLE
Can't print symbols with ESRI's print service

### ISSUE THREAD

**Issue by mihuman** [nickcam/DirectionalLineSymbol#1]
Hi Nick,

Once again: thank you so much for sharing your code on directional line symbols! I've been using your approach for some custom graphics of my own and it's been working super good for me.

But when using the graphics in an Web AppBuilder app, I discovered that I can't print the graphics with the Print widget. It either ends up throwing an error (for your DirectionalLine grahics) or just prints the basemap (for my graphics). According to discussions [here](https://geonet.esri.com/message/577232) and [here](https://geonet.esri.com/message/577234), it is because ESRI's print service cannot handle custom graphics and they should be converted to ESRI symbols.

I'd be very interested in an upgrade.

Thanks,
Mihkel

**Comment by nickcam** [comment]
Hi Mikhel,

So I've had a look at this...it was actually pretty simple to fix. 
I just need to test it in Web AppBuilder using the print widget, the print task on our ArcGIS server isn't working at the moment. 

Will hopefully commit the fix within the next week.

Thanks,
Nick

**Comment by nickcam** [comment]
Hi Mikhel, just committed a fix for this. Let me know how it goes.

**Comment by mihuman** [comment]
Hi Nick!

Thank you for the fix! That's a really clever use of SimpleMarkerSymbols and converting them to JSON!

As I am using kind of a polyline/polygon variety of your approach, I'll soon dig into your new code and see how I could make the appropriate changes for my code.

Thanks again,
Mihkel
