### ISSUE TITLE
The browser always complains

### ISSUE THREAD

**Issue by kingder-c** [nickcam/DirectionalLineSymbol#10]
TypeError: Cannot read property '_div' of undefined
    at Object._drawDirection (DirectionalLineSymbol.js:250)
    at Object.<anonymous> (DirectionalLineSymbol.js:191)

**Comment by nickcam** [comment]
Hey man, what version of the api are you using? I've tried it on 3.18 and greater and it's working fine.
If you are using version 3.18 or greater do you have somewhere you can demo the problem...a plunk or something?
