### ISSUE TITLE
update to api 4.4

### ISSUE THREAD

**Issue by shayts** [nickcam/DirectionalLineSymbol#11]
Hi,
Any change you will update this project to api 4.4?

**Comment by nickcam** [comment]
Hi, no sorry...hadn't planned on porting this to the 4.x apis. 
There's a lot of fundamental differences between 3 and 4 that I don't think extending a symbol class would work very well. So to get the same sort of functionality in v4 a new project would be best. This may be something I (or someone else) does in the near future. Thanks!

**Comment by abdulk1** [comment]
Do you know if anyone has converted this to v4 yet?

**Comment by nickcam** [comment]
Hi, no not that I'm aware of sorry. You could try checking out any of the forks to see if it's been done.
