### ISSUE TITLE
Repeated animation loop

### ISSUE THREAD

**Issue by purnamasari** [nickcam/DirectionalLineSymbol#12]
Hi dude, I found your repository, and that helps me a lot on my gis project, I dunno if this is an issues or not, but I wanna ask you how to make animation with only one arrow, not creating the graphic that we've made before? Thank you.

**Comment by purnamasari** [comment]
Oh, nevermind. I found a solution. Try to add `onEnd: function(){
                       fx.fadeOut({
                           node: path
                       }).play()
                   }` on the `var fi = fx.fadeIn({
                    node: path,
                    duration: dur,`

**Comment by nickcam** [comment]
Ok cool. Glad you worked it out!
