### ISSUE TITLE
can it support openlayers?

### ISSUE THREAD

**Issue by dyh333** [nickcam/DirectionalLineSymbol#13]
hi, @nickcam . can it support openlayers? or only fit arcgis js api?
thanks

**Comment by nickcam** [comment]
Hi @dyh333, no it's extending the arcgis js api, and as such is using it for everything except it's own internal functions. Absolutely no chance it would work with with other apis. 

It's essentially just DOM manipulation via event handlers though, so you could take the principles and try and create versions for other apis.
