### ISSUE TITLE
Arrow disapear when going out from the frame

### ISSUE THREAD

**Issue by zer0890** [nickcam/DirectionalLineSymbol#15]
If i add a layer with 2 polyline graphics (first a basic polyline, and the second graphic will be the DLS as the DLS would be on the basic polyline), with the same path for each polyline, and i am going out from the frame and go back, arrow will be under the first polyline instead of being on.

You can check it easily if the first basic polyline has a big width, you wont see any arrow.

**Comment by nickcam** [comment]
Are you able to create a repro example, using plunkr or stackblitz or anything like that? Thanks.
