### ISSUE TITLE
Unable to load DirectionalLineSymbol in arcigs loadmodules method

### ISSUE THREAD

**Issue by LXMin** [nickcam/DirectionalLineSymbol#16]
I use the newest arcgis api to load the module i need, as "loadmodule()", but after I load the js file of DirectionalLineSymbol, it seems that there is an error called "DirectionalLineSymbol is not a construction". If that because the define not suitable with the loadmodules method?

**Comment by LXMin** [comment]
The demo has been 3 years ago, is there any body help to submit a new demo with the arcgis new api? thanks

**Comment by nickcam** [comment]
Hey @LXMin - Do you mean with v4.x of the arcgis api? 
If so it certainly won't work with v4, Would require a whole new library to support v4.

If you mean the latest version of 3.x, then perhaps put together a plunkr or jsbin or some sort of page that demos the problems live and I'll take a look. 

As you've noticed this library doesn't get a lot of support. I don't use it anymore...I doubt many people or possibly anyone really is still using it.
