### ISSUE TITLE
Application for feature layers

### ISSUE THREAD

**Issue by dustwhirl** [nickcam/DirectionalLineSymbol#4]
Can a DirectionalLineSymbol be applied to a Feature Layer using the setRenderer function? I've done that, everything looks fine with no errors, however, I do not see the symbology in the map.

**Comment by nickcam** [comment]
Hi, I'm not 100% sure on what you mean. Do you mean using it as a symbol inside of a renderer, or adding the symbol directly to the setRenderer() call? Can you post some code please.
Thanks.

**Comment by dustwhirl** [comment]
Thanks for the response. Here's what I'm trying to do...

```
              var fl = new FeatureLayer(item.url, {
                id: item.id,
                mode: esri.layers.FeatureLayer.MODE_ONDEMAND,
                visible: item.visible,
                showLabels: item.layer.useLabel,
                opacity: opacity,
                outFields: outFields
            });

                     var options = {
                        style: SimpleLineSymbol.STYLE_SOLID,
                        color: new Color([51, 102, 255]),
                        width: 2,
                        directionSymbol: 'arrow1',
                        directionPixelBuffer: 60,
                        directionColor: new Color([204, 51, 0]),
                        directionSize: 14
                    };
                    var renderer = new DirectionalLineSymbol(options);
                    fl.setRenderer(renderer);
```

**Comment by dustwhirl** [comment]
Sometimes all it takes is a quick re-look at what I was trying to do. I have it working now. Thanks!

var renderer = new DirectionalLineSymbol(options);
fl.setRenderer(renderer);

should have been:

var dls = new DirectionalLineSymbol(options);
var renderer = new SimpleRenderer(dls);
fl.setRenderer(renderer);

**Comment by nickcam** [comment]
Good stuff, yeah that's what I thought might have been the issue...the symbol is used in a renderer, it isn't a renderer itself :). Glad you got it sorted.
