### ISSUE TITLE
Add a License?

### ISSUE THREAD

**Issue by lobsteropteryx** [nickcam/DirectionalLineSymbol#6]
We'd love to use this, and are happy to give credit, but the lack of a license is problematic.  Would you consider putting this under MIT?  That would remove any ambiguity around copyright, etc.

Happy to submit a PR if you're willing.

**Comment by nickcam** [comment]
No worries, MIT license just added.

**Comment by lobsteropteryx** [comment]
Beautiful, thanks for the great work!
