### ISSUE TITLE
Directions shift away from lines in IE8

### ISSUE THREAD

**Issue by eamiear** [nickcam/DirectionalLineSymbol#7]
When i open the example page (http://directionallinesymbol.azurewebsites.net/) in IE8, zooming in and dragging, the directions shift away from the polylines. How to fix it?
![2016-08-04_103035](https://cloud.githubusercontent.com/assets/13484877/17389227/c3bfd6d4-5a34-11e6-97e9-953b3b348c8a.jpg)

**Comment by nickcam** [comment]
Hi @eamiear,

I don't have IE8 and the only way I can test it is to use the F12 tools in IE11 to emulate it. 
When I do that I don't see any graphics at all actually.

To be honest I'm not going to bother looking at fixing it for IE8 - you're more than welcome to though - it appears to be working in IE9 and above, and realistically I would probably only bother supporting >= IE10.

Sorry about that. 

Thanks,
Nick

**Comment by eamiear** [comment]
Thanks for the reply, maybe I should give up the use of IE8.
